from sqlalchemy.ext.asyncio import AsyncSession
from typing import List, Dict, Any, NamedTuple
import logging
from datetime import datetime

from .embedding_service import EmbeddingService
from .content_service import ContentService

logger = logging.getLogger(__name__)

class RAGResponse(NamedTuple):
    response: str
    context_used: str
    sources: List[Dict[str, Any]]

class RAGService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.embedding_service = EmbeddingService()
        self.content_service = ContentService(db)

    async def get_response(self, query: str, context: str = None) -> RAGResponse:
        """Generate a response to a query using RAG (Retrieval Augmented Generation)"""
        try:
            # Get relevant content from the vector database
            relevant_content = await self.embedding_service.get_relevant_content(query, limit=5)

            # Prepare context from retrieved content
            context_text = ""
            sources = []

            if relevant_content:
                # Combine the most relevant content pieces
                for item in relevant_content:
                    context_text += f"\n\nFrom {item.get('title', 'Unknown Source')}:\n{item['text_content']}"
                    sources.append({
                        "id": item["id"],
                        "title": item.get("title", ""),
                        "content_snippet": item["text_content"][:200] + "..." if len(item["text_content"]) > 200 else item["text_content"],
                        "relevance_score": item["relevance_score"]
                    })
            elif context:
                # If no relevant content found but context was provided, use the provided context
                context_text = context
                sources.append({
                    "id": "provided_context",
                    "title": "Provided Context",
                    "content_snippet": context[:200] + "..." if len(context) > 200 else context,
                    "relevance_score": 1.0
                })

            # If we have context, generate a response using it
            if context_text.strip():
                # In a real implementation, this would call an LLM API
                # For now, we'll create a simple response based on the context
                response = await self._generate_response_with_context(query, context_text)
                context_used = context_text
            else:
                # If no context is available, respond that we can't answer
                response = "I don't have sufficient information from the textbook to answer your question. Please check the relevant chapters for more information."
                context_used = ""

            return RAGResponse(
                response=response,
                context_used=context_used,
                sources=sources
            )
        except Exception as e:
            logger.error(f"Error generating RAG response: {e}")
            raise

    async def _generate_response_with_context(self, query: str, context: str) -> str:
        """Generate a response using the provided context"""
        # This is a simplified implementation
        # In a real application, this would call an LLM API like OpenAI
        # For now, we'll return a response that acknowledges the context was used

        # Simple implementation that just confirms the query and mentions we used context
        return f"I found information related to your question '{query}'. Based on the textbook content, here's what I can tell you: [Response would be generated by an LLM using the provided context]. This information is sourced from the textbook content."

    async def search_content(self, query: str, limit: int = 5) -> List[Dict[str, Any]]:
        """Search textbook content using RAG"""
        try:
            # Get relevant content from the vector database
            relevant_content = await self.embedding_service.get_relevant_content(query, limit=limit)

            results = []
            for item in relevant_content:
                results.append({
                    "id": item["id"],
                    "title": item.get("title", "Untitled"),
                    "content_snippet": item["text_content"][:300] + "..." if len(item["text_content"]) > 300 else item["text_content"],
                    "relevance_score": item["relevance_score"],
                    "url": f"/docs/{item.get('chapter_slug', 'unknown')}" if item.get("chapter_slug") else "#"
                })

            return results
        except Exception as e:
            logger.error(f"Error searching content: {e}")
            raise

    async def index_textbook_content(self, chapter_id: str, title: str, content: str, slug: str):
        """Index textbook content for RAG search"""
        try:
            # Process the chapter to create embeddings
            embeddings = await self.embedding_service.process_textbook_chapter(
                chapter_id=chapter_id,
                title=title,
                content=content,
                slug=slug
            )

            logger.info(f"Indexed chapter {chapter_id} with {len(embeddings)} embeddings for RAG search")
            return embeddings
        except Exception as e:
            logger.error(f"Error indexing textbook content: {e}")
            raise

    async def update_indexed_content(self, chapter_id: str, new_content: str):
        """Update the indexed content for a chapter"""
        try:
            # First delete existing embeddings for this content
            await self.embedding_service.delete_content_embeddings(chapter_id)

            # Then re-index with new content
            # We would need to fetch the title and slug from the database
            chapter = await self.content_service.get_chapter_by_id(chapter_id)
            if chapter:
                embeddings = await self.embedding_service.process_textbook_chapter(
                    chapter_id=chapter_id,
                    title=chapter.title,
                    content=new_content,
                    slug=chapter.slug
                )
                return embeddings

            return []
        except Exception as e:
            logger.error(f"Error updating indexed content: {e}")
            raise

    async def delete_indexed_content(self, content_id: str):
        """Delete indexed content"""
        try:
            await self.embedding_service.delete_content_embeddings(content_id)
            logger.info(f"Deleted indexed content for ID: {content_id}")
        except Exception as e:
            logger.error(f"Error deleting indexed content: {e}")
            raise